# -*- coding: utf-8 -*-
"""task 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdEk2ssv_Hr4IKyoZ33n-okevvhQccBM
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/PROJECT/healthcare_dataset.csv")

df.info()

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])


df['Stay Duration'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

billing_data = pd.pivot_table(
    df,
    values='Billing Amount',
    index='Medical Condition',
    columns='Insurance Provider',
    aggfunc='sum'
)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6)
)
plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount',
    hue='Insurance Provider',
    cut=0
)

plt.title('Billing Amount Distribution by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

monthly_admissions = (
    df.set_index('Date of Admission')
      .resample('ME')
      .size()
)

print(monthly_admissions.head())

plt.figure(figsize=(14,6))

plt.plot(
    monthly_admissions.index,
    monthly_admissions.values
)

plt.title('Monthly Patient Admissions Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Admissions')
plt.grid(True)
plt.tight_layout()
plt.show()

corr_data = df[
    ['Age', 'Stay Duration', 'Billing Amount']
]
correlation = corr_data.corr()
print(correlation)

plt.figure(figsize=(8,6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.4f'
)

plt.title('Correlation Matrix: Age, Stay Duration and Billing Amount')
plt.tight_layout()
plt.show()

condition_billing = (
    df.groupby('Medical Condition')['Billing Amount']
      .mean()
      .sort_values(ascending=False)
)

print(condition_billing)

plt.figure(figsize=(10,6))

condition_billing.plot(kind='bar')

plt.title('Average Billing Amount by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Average Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

provider_billing = (
    df.groupby('Insurance Provider')['Billing Amount']
      .mean()
      .sort_values(ascending=False)
)

print(provider_billing)