# -*- coding: utf-8 -*-
"""task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvVQYpBq8Ufo8VzMS0nRq6-ylVxeRlNM
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/PROJECT/healthcare_dataset.csv")

df.head()

df.tail()

df.info()

df.isnull()

cat_cols = [
    'Gender',
    'Blood Type',
    'Medical Condition',
    'Admission Type',
    'Medication',
    'Test Results'
]

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

print(df[cat_cols].head())

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission']
)

df['Discharge Date'] = pd.to_datetime(
    df['Discharge Date']
)

print(df[['Date of Admission', 'Discharge Date']].head())

df['Stay Days'] = (
    df['Discharge Date'] -
    df['Date of Admission']
).dt.days

print(df[['Date of Admission',
          'Discharge Date',
          'Stay Days']].head())

demographics = pd.crosstab(
    df['Medical Condition'],
    df['Gender']
)

print(demographics)

admission_counts = df['Admission Type'].value_counts()
print(admission_counts)

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x='Admission Type'
)

plt.title('Patient Admissions by Type')
plt.xlabel('Admission Type')
plt.ylabel('Number of Patients')
plt.show()

print(df['Billing Amount'].describe())

print("Mean:", df['Billing Amount'].mean())
print("Median:", df['Billing Amount'].median())
print("Standard Deviation:", df['Billing Amount'].std())
print("Minimum:", df['Billing Amount'].min())
print("Maximum:", df['Billing Amount'].max())

print(df['Stay Days'].describe())

plt.figure(figsize=(10,6))

sns.histplot(
    df['Stay Days'],
    bins=30,
    kde=True
)

plt.title('Distribution of Hospital Stay Duration')
plt.xlabel('Stay Days')
plt.ylabel('Number of Patients')
plt.show()

plt.figure(figsize=(10,6))

sns.histplot(
    df['Billing Amount'],
    bins=30,
    kde=True
)

plt.title('Distribution of Patient Billing Amounts')
plt.xlabel('Billing Amount')
plt.ylabel('Number of Patients')
plt.show()