# -*- coding: utf-8 -*-
"""AAPL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDGYB9VlE6ju8RQee48tYbbrGZjv1JfL
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("/content/drive/MyDrive/PROJECT/AAPL.xlsx")

df.head()

df.tail()

df.info()

print(len(df.columns))

df.isnull()

df.duplicated()

df["Daily_Delta"]=df["Close"]-df["Open"]
display(df.head())