# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rruY8-9ssjvGUdNUKMnRAmyeVTgMf_qu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/BIG DATA /SuperStore.csv.csv")

df.head()

df.info()

df.describe()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df.info()

df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

df.head()

df['Category'].unique()

df.isnull().sum()

category_sales = (df.groupby('Category')['Sales Amount'].sum())
category_sales

category_sales.plot( kind='bar',figsize=(8,5))
plt.title("Sales by Category")
plt.ylabel("Total Sales")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Sales Amount'],bins=30)
plt.title("Sales Distribution")
plt.show()