# -*- coding: utf-8 -*-
"""task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2h4ncpuyTpenb5l2tXfX3QtK69ju6fI
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/drive/MyDrive/PROJECT/AAPL.xlsx")

df.info()

df.head()

df.tail()

df.isnull()

df['MA20'] = df['Close'].rolling(window=20).mean()
df['MA50'] = df['Close'].rolling(window=50).mean()

print(df[['Date', 'Close', 'MA20', 'MA50']].tail())

plt.figure(figsize=(12,6))

plt.plot(df['Date'], df['Open'], label='Open')
plt.plot(df['Date'], df['High'], label='High')
plt.plot(df['Date'], df['Low'], label='Low')
plt.plot(df['Date'], df['Close'], label='Close')

plt.title('AAPL OHLC Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12,5))

plt.plot(df['Date'], df['Volume'])

plt.title('AAPL Trading Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Trading Volume')
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))

plt.plot(df['Date'], df['Close'], label='Daily Close')
plt.plot(df['Date'], df['MA20'], label='20-Day Moving Average')
plt.plot(df['Date'], df['MA50'], label='50-Day Moving Average')

plt.title('AAPL Closing Price with Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()

df['Returns'] = df['Close'].pct_change()

print(df[['Date', 'Close', 'Returns']].head(10))

import seaborn as sns
plt.figure(figsize=(10,6))

sns.histplot(
    df['Returns'].dropna(),
    kde=True,
    bins=30
)

plt.title('AAPL Returns Distribution')
plt.xlabel('Returns')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()