# -*- coding: utf-8 -*-
"""task 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPhISAEXVRD_3dZblCZumTPRbv0BKu7M
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns

df = pd.read_csv("/content/drive/MyDrive/PROJECT/studentperformance_preprocessed.csv")

df.head()

df.tail()

df.info()

df.isnull()

avg_scores = df.groupby(
    ['parental level of education', 'lunch']
)[['math score', 'reading score', 'writing score']].mean()
avg_scores.plot(kind='bar', figsize=(12,6))

plt.title("Average Test Scores by Parental Education and Lunch Type")
plt.xlabel("Parental Education and Lunch Type")
plt.ylabel("Average Score")
plt.xticks(rotation=45, ha='right')
plt.legend(title="Subjects")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='math score'
)
plt.title("Math Score Variance by Test Preparation")
plt.xlabel("Test Preparation Course")
plt.ylabel("Math Score")
plt.show()

score_data = df.melt(
    id_vars=['test preparation course'],
    value_vars=['math score', 'reading score', 'writing score'],
    var_name='Subject',
    value_name='Score'
)

plt.figure(figsize=(10,6))

sns.boxplot(
    data=score_data,
    x='Subject',
    y='Score',
    hue='test preparation course'
)

plt.title("Score Variance by Test Preparation Course")
plt.xlabel("Subject")
plt.ylabel("Score")
plt.legend(title="Test Preparation")
plt.tight_layout()
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x='math score',
    y='reading score'
)

plt.title("Math Score vs Reading Score")
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x='math score',
    y='writing score'
)

plt.title("Math Score vs Writing Score")
plt.xlabel("Math Score")
plt.ylabel("Writing Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x='reading score',
    y='writing score'
)

plt.title("Reading Score vs Writing Score")
plt.xlabel("Reading Score")
plt.ylabel("Writing Score")
plt.show()

scores = df[['math score', 'reading score', 'writing score']]
corr = scores.corr()
plt.figure(figsize=(7,5))
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)

plt.title("Correlation Heatmap of Math, Reading and Writing Scores")
plt.show()

